---
- hosts: all

  become: true
  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest

    - name: Update package manager cache
      dnf:
        update_cache: yes